name: gofund
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_stripe: ^11.4.0
  hive_flutter: ^1.1.0
  http: ^1.3.0
  provider: ^6.1.2
  supabase_flutter: ^2.8.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/
