name: gofund
description: "An app that connects schools with donors for transparent and efficient fundraising."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_stripe: ^11.4.0
  hive_ce: ^2.9.0
  hive_ce_flutter: ^2.2.0
  http: ^1.3.0
  provider: ^6.1.2
  supabase_flutter: ^2.8.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
  hive_ce_generator: ^1.8.2
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/
